feat: created allocations page
yearn/yearn-watch pull request #129
Opened 2022-10-10 06:29 UTC by bogdanuch41

### Description

In this PR I have created a page to monitor the amount of allocations for each protocol for certain network or all network combined. On the page you can see a list of protocols with such information as: Protocol name, Total value locked(in $ and %), Strategies amount that have this protocol as allocation point, Strategies amount that have any tokens allocated from this protocol. Also, if you click on any Issue - you will get a list of available strategies, sorted by the tvl, showing which part of Protocol tvl was allocated to this strategy.

### Related Issue

#8

2022-10-13 08:44 UTC, Majorfi commented
Hey!
Thank you for your PR!

Here are a few comments:
- This looks like a good job
- Could you replace the Icon by this one ?
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path d="M294.4 44.8c6-8.1 15.5-12.8 25.6-12.8H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H336L249.6 211.2c-6 8.1-15.5 12.8-25.6 12.8H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H208L294.4 44.8zM141.9 320H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H216.5l57.6 96H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H256c-11.2 0-21.7-5.9-27.4-15.5L141.9 320z"/></svg>
```
- Would it be possible to group all `0.00%` in a subgroup, just like on [this](https://yearn-watch-git-fork-yozh-io-main.yearn.farm/vault/0xdb25cA703181E7484a155DD612b06f57E12Be5F0) page for example? (in the strategies tab, `Empty Allocations`)

2022-10-24 06:08 UTC, bogdanuch41 commented
> Hey! Thank you for your PR!
> 
> Here are a few comments:
> 
> * This looks like a good job
> * Could you replace the Icon by this one ?
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path d="M294.4 44.8c6-8.1 15.5-12.8 25.6-12.8H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H336L249.6 211.2c-6 8.1-15.5 12.8-25.6 12.8H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H208L294.4 44.8zM141.9 320H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H216.5l57.6 96H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H256c-11.2 0-21.7-5.9-27.4-15.5L141.9 320z"/></svg>
> ```
> 
> * Would it be possible to group all `0.00%` in a subgroup, just like on [this](https://yearn-watch-git-fork-yozh-io-main.yearn.farm/vault/0xdb25cA703181E7484a155DD612b06f57E12Be5F0) page for example? (in the strategies tab, `Empty Allocations`)



> Hey! Thank you for your PR!
> 
> Here are a few comments:
> 
> * This looks like a good job
> * Could you replace the Icon by this one ?
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path d="M294.4 44.8c6-8.1 15.5-12.8 25.6-12.8H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H336L249.6 211.2c-6 8.1-15.5 12.8-25.6 12.8H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H208L294.4 44.8zM141.9 320H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H216.5l57.6 96H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H256c-11.2 0-21.7-5.9-27.4-15.5L141.9 320z"/></svg>
> ```
> 
> * Would it be possible to group all `0.00%` in a subgroup, just like on [this](https://yearn-watch-git-fork-yozh-io-main.yearn.farm/vault/0xdb25cA703181E7484a155DD612b06f57E12Be5F0) page for example? (in the strategies tab, `Empty Allocations`)

Sorry, didn't see the comment until recently. Is it okay now?

2022-10-24 09:43 UTC, Majorfi requested changes
Hey!
Thank you for the changes!
Some more little stuff :)

2022-10-24 09:43 UTC, Majorfi commented on components/icons/IconAllocations.tsx
> +			<path d={'M294.4 44.8c6-8.1 15.5-12.8 25.6-12.8H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H336L249.6 211.2c-6 8.1-15.5 12.8-25.6 12.8H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H208L294.4 44.8zM141.9 320H
```suggestion
			<path d={'M294.4 44.8c6-8.1 15.5-12.8 25.6-12.8H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H336L249.6 211.2c-6 8.1-15.5 12.8-25.6 12.8H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H208L294.4 44.8zM141.9 320H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H216.5l57.6 96H544c17.7 0 32 14.3 32 32s-14.3 32-32 32H256c-11.2 0-21.7-5.9-27.4-15.5L141.9 320z'} fill={'currentcolor'} />
```

2022-10-24 09:43 UTC, Majorfi commented on contexts/useWatch.tsx
> +import {options} from '../components/Header';
```suggestion
import {options} from 'components/Header';
```

2022-10-24 09:43 UTC, Majorfi commented on contexts/useWatch.tsx
> +					console.log(`Can't get info on ${chain.label} chain.\n`, e);
```suggestion
					console.error(`Can't get info on ${chain.label} chain.\n`, e);
```

2022-10-24 09:43 UTC, Majorfi commented on pages/allocations.tsx
> +	return (
Formatting here looks weird

2022-10-24 09:43 UTC, Majorfi commented on pages/allocations.tsx
> +					onClick={(): void=>set_chain(chain)}
```suggestion
					onClick={(): void=> set_chain(chain)}
```

2022-10-24 09:43 UTC, Majorfi commented on pages/allocations.tsx
> +					className={`text-black-600 cursor-pointer rounded-[12px] py-2 px-4 hover:bg-neutral-300${chain === selectedChain ? 'transition-color bg-neutral-300' : 'transition-color bg-neutral-300/50'}`}
```suggestion
					className={`text-black-600 cursor-pointer rounded-[12px] py-2 px-4 hover:bg-neutral-300 ${chain === selectedChain ? 'transition-color bg-neutral-300' : 'transition-color bg-neutral-300/50'}`}
```

2022-10-24 09:43 UTC, Majorfi commented on pages/allocations.tsx
> +}
Could you move theses out of the `page` folder?
Page folder should not be imported by any other file :)

2022-10-24 09:43 UTC, Majorfi commented on pages/allocations.tsx
> +				vault.strategies.forEach((strategy): void => {
FYI, `forEach` should be avoided and classing `for loop` should be prefered as this could lead to some race-conditions error.
No need to change here for now, but let's keep an eye on that if we notice some errors

2022-10-24 09:44 UTC, Majorfi commented
@storming0x could you take a look on the preview URL and see if all looks good to you ? 🙏

2022-10-24 17:21 UTC, storming0x commented
> @storming0x could you take a look on the preview URL and see if all looks good to you ? 🙏

looks great!, just one Q, why makerDAO has the gen lev comp strat listed here, i think it doesnt interact with maker
![Screen Shot 2022-10-24 at 11 20 49](https://user-images.githubusercontent.com/6074987/197587378-4a7083dc-c541-4928-b310-8dfede7b60d6.png)

2022-10-26 03:46 UTC, bogdanuch41 commented
> > @storming0x could you take a look on the preview URL and see if all looks good to you ? pray
> 
> looks great!, just one Q, why makerDAO has the gen lev comp strat listed here, i think it doesnt interact with maker ![Screen Shot 2022-10-24 at 11 20 49](https://user-images.githubusercontent.com/6074987/197587378-4a7083dc-c541-4928-b310-8dfede7b60d6.png)

![image](https://user-images.githubusercontent.com/92035951/197929694-c599ab85-c842-4732-a039-4161f3220560.png)
Well, I'm just filtering data. For example, here, I just filtered vaults only with GenLevCompV3 strategy to search, looked into the first one found and MarkerDAO is listed as on of it's protocols

2022-10-26 03:55 UTC, bogdanuch41 commented on pages/allocations.tsx
> +	return (
Is it looking okay now? I fixed it to how such functions were done in project before

2022-10-26 03:57 UTC, bogdanuch41 commented on pages/allocations.tsx
> +				vault.strategies.forEach((strategy): void => {
Okay, tell me if any problem will occur.

2022-10-26 06:12 UTC, storming0x commented
> > > @storming0x could you take a look on the preview URL and see if all looks good to you ? pray
> > 
> > 
> > looks great!, just one Q, why makerDAO has the gen lev comp strat listed here, i think it doesnt interact with maker ![Screen Shot 2022-10-24 at 11 20 49](https://user-images.githubusercontent.com/6074987/197587378-4a7083dc-c541-4928-b310-8dfede7b60d6.png)
> 
> ![image](https://user-images.githubusercontent.com/92035951/197929694-c599ab85-c842-4732-a039-4161f3220560.png) @storming0x , I'm actually just processing data received from `ydaemon.yearn.finance`. For example, here, I just filtered vaults only with GenLevCompV3 strategy, looked into the first one found and MarkerDAO is listed as on of it's protocols(I would have shown it on page with link, but it's too hard to read pure json without any stylization)

sounds good, i guess this is an issue on data from ydaemon @Majorfi ? but i guess we can merge this and debug later if needed

2022-10-27 08:49 UTC, bogdanuch41 commented on pages/allocations.tsx
> +	return (
So, @Majorfi is it good now?

2022-10-27 16:00 UTC, storming0x approved these changes

2022-10-31 09:49 UTC, Majorfi approved these changes
LGTM! Thank you for this PR! As suggested by Storm, we can iterate from it if more changes are required!

2022-10-31 09:50 UTC, merged