fix: Change data fetched from ydata to ydaemon
yearn/yearn-watch pull request #131
Opened 2022-10-19 02:23 UTC by huggingbot

### Description
Change data fetched from yData to yDaemon

### Motivation and Context
The risk metric in yData has migrated to yDaemon but yWatch is still pointing to yData

### How Has This Been Tested?
Running locally

2022-10-19 11:37 UTC, kyhoon commented
will remove the redundant check of the risk group criteria like the nameLikes, since they are already being parsed from yDaemon

2022-10-30 13:00 UTC, kyhoon commented
🔥 🔥 🔥 @Majorfi 🔥 🔥 🔥

2022-10-31 11:11 UTC, Majorfi requested changes
Very minor changes :)

2022-10-31 11:11 UTC, Majorfi commented on pages/risk.tsx
> +				let _obj: { [key: string]: TRiskGroup } = {...obj};
```suggestion
				let _obj: {[key: string]: TRiskGroup} = {...obj};
```

2022-10-31 11:11 UTC, Majorfi commented on pages/risk.tsx
> +					if (!label) return;
```suggestion
					if (!label) {
						return;
					}
```

2022-10-31 11:11 UTC, Majorfi commented on pages/risk.tsx
> +					const strategyCriteria = [...(_obj[id]?.criteria.strategies ?? [])];
```suggestion
					const strategyCriteria = [...(_obj[id]?.criteria?.strategies ?? [])];
```

2022-10-31 11:11 UTC, Majorfi commented on pages/risk.tsx
> +				vault.strategies.forEach((strategy): void => {
The `forEach` loop should be avoided most of the time as it could lead to race conditions issue. Not a big deal right now, but will try to find a lint rule for that
You should prefer a `for of` type of loop :)

2022-10-31 15:35 UTC, Majorfi requested changes

2022-10-31 15:35 UTC, Majorfi commented on pages/risk.tsx
> +			const riskGroup = vaultWithRiskGroup.reduce((obj, vault): { [key: string]: TRiskGroup }  => {
```suggestion
			const riskGroup = vaultWithRiskGroup.reduce((obj, vault): {[key: string]: TRiskGroup}  => {
```

2022-10-31 15:35 UTC, Majorfi commented on pages/risk.tsx
> +			const riskGroup = vaultWithRiskGroup.reduce((obj, vault): { [key: string]: TRiskGroup }  => {
Sorry missed this one

2022-10-31 15:39 UTC, Majorfi requested changes

2022-10-31 15:39 UTC, Majorfi commented on pages/risk.tsx
> +				for (const { risk, address } of vault.strategies) {
```suggestion
				for (const {risk, address} of vault.strategies) {
```

2022-11-02 16:37 UTC, storming0x approved these changes
Preview LGTM!

2022-11-03 08:28 UTC, Majorfi approved these changes

2022-11-03 08:28 UTC, merged