Vault name instead of vault symbol inside descriptions
yearn/yearn-watch pull request #136
Opened 2022-11-24 00:00 UTC by ai-slave

fixes #118

2022-11-24 08:49 UTC, Majorfi commented
Hey @ai-slave!
Thank you for your PR!
Could you fix the [type error](https://github.com/yearn/yearn-watch/actions/runs/3536556920/jobs/5940498371)?

2022-11-24 09:27 UTC, ai-slave commented
Yeah, sorry push didn't went trough yesterday :(

2022-11-24 21:55 UTC, ai-slave commented
Seems good now

2022-12-14 10:28 UTC, Majorfi approved these changes

2022-12-14 10:29 UTC, Majorfi requested changes

2022-12-14 10:29 UTC, Majorfi commented on components/sections/strategies/SectionAbout.tsx
> +	console.log(currentVault);
```suggestion
```

2022-12-16 15:52 UTC, Majorfi approved these changes

2022-12-16 15:52 UTC, merged